In [1]:
import torch

In [10]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad= True)
b = torch.randn(3, requires_grad= True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(w)
print(b)

tensor([[-0.1433, -0.1264, -0.5005],
        [ 0.4946,  0.3156, -0.7210],
        [-1.9058,  0.7028,  0.0261],
        [ 1.1659, -1.4192, -0.0924],
        [-2.4447,  1.0768,  0.7390]], requires_grad=True)
tensor([ 0.4367, -0.9705, -0.4378], requires_grad=True)


In [11]:
print(f'Gradient function for z = {z.grad_fn}')
print(f'Gradient function for loss = {loss.grad_fn}')

Gradient function for z = <AddBackward0 object at 0x7f9fa128cd90>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7f9fa128c490>


In [12]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0278, 0.1321, 0.0905],
        [0.0278, 0.1321, 0.0905],
        [0.0278, 0.1321, 0.0905],
        [0.0278, 0.1321, 0.0905],
        [0.0278, 0.1321, 0.0905]])
tensor([0.0278, 0.1321, 0.0905])


In [14]:
z = torch.matmul(x, w)+ b
print(z.requires_grad)

with torch.no_grad():
  z = torch.matmul(x, w) + b
print(z.requires_grad)

True
False


In [16]:
z = torch.matmul(x, w) + b
z_det = z.detach() #same with the torch.no_grad
print(z_det.requires_grad)

False


In [ ]:
#torch use Jacobian matrix and Jacobian to do the difference

In [24]:
inp = torch.eye(5, requires_grad= True) #torch.eye 建立一個像單位矩陣的tensor
print(f'inp\n{inp}\n')
out = (inp + 1).pow(2)
print(f'out\n{out}\n')
out.backward(torch.ones_like(inp), retain_graph= True) #微分一次的係數
print(f'First call\n{inp.grad}') 
out.backward(torch.ones_like(inp), retain_graph= True) #微分兩次的係數和
print(f'\nSecond call\n{inp.grad}')
inp.grad.zero_() #重設微分和
out.backward(torch.ones_like(inp), retain_graph= True)
print(f'\ncall after zeroing gradients\n{inp.grad}')

inp
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], requires_grad=True)

out
tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.],
        [1., 1., 1., 1., 4.]], grad_fn=<PowBackward0>)

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
