In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array([[1, 2], [3, 4]])
x_np = torch.from_numpy(np_array)

In [4]:
x_ones = torch.ones_like(x_data, dtype = torch.float)
print(f'Ones Tensor: \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype= torch.float)
print(f'Random Tensor: \n {x_rand} \n')

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]]) 

Random Tensor: 
 tensor([[0.2840, 0.4117],
        [0.5624, 0.6200]]) 



In [5]:
shape = (2, 3,) #最後一個逗點可以省略
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor}')

Random Tensor: 
 tensor([[0.8290, 0.3060, 0.2175],
        [0.9081, 0.9071, 0.9637]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3, 4)
print(f'shape of tensor: {tensor.shape}')
print(f'datatype of tensor: {tensor.dtype}')
print(f'device tensor is stored on: {tensor.device}')

shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor is stored on: cpu


In [7]:
!nvidia-smi

Fri Mar 11 08:50:49 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P8    29W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [8]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  device = 'cuda' if torch.cuda.is_available() else 'cpu'
  print(device)

cuda


In [9]:
tensor = torch.ones(4, 4)
tensor[:, 0] = 0
tensor[:, 1] = 1
tensor[:, 2] = 2
tensor[:, 3] = 3
print(f'first row: {tensor[0]}')
print(f'first column: {tensor[:, 0]}')
print(f'last column: {tensor[..., -1]}') # ... 

print(tensor)

first row: tensor([0., 1., 2., 3.])
first column: tensor([0., 0., 0., 0.])
last column: tensor([3., 3., 3., 3.])
tensor([[0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.]])


In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim= 1)
t2 = torch.cat([tensor, tensor, tensor], dim= 0)
print(t1)
print(t2)

tensor([[0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.],
        [0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.],
        [0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.],
        [0., 1., 2., 3., 0., 1., 2., 3., 0., 1., 2., 3.]])
tensor([[0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.]])


In [11]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(tensor.T, '\n')
print(y1, '\n')
print(f'{y2} \n ')
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out= y3)
print(y3, '\n')
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out= z3)

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]]) 

tensor([[14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.]]) 

tensor([[14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.]]) 
 
tensor([[14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.],
        [14., 14., 14., 14.]]) 



tensor([[0., 1., 4., 9.],
        [0., 1., 4., 9.],
        [0., 1., 4., 9.],
        [0., 1., 4., 9.]])

In [12]:
agg = tensor.sum()
agg_item = agg.item()
print(agg, agg_item, type(agg), type(agg_item))

tensor(24.) 24.0 <class 'torch.Tensor'> <class 'float'>


In [13]:
np_array = np.array([[1, 2], [3, 4]])
x_np = torch.from_numpy(np_array)

np_array = np.array([[5, 6], [7, 8]])
y_np = torch.from_numpy(np_array)

print(x_np)
x_np.copy_(y_np)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [14]:
x = torch.tensor(np.array([[1, 2], [3, 4]]))
z = x.add(5)
print(z,'\n', x)
y = x.add_(5)
print(y, '\n', x)


tensor([[6, 7],
        [8, 9]]) 
 tensor([[1, 2],
        [3, 4]])
tensor([[6, 7],
        [8, 9]]) 
 tensor([[6, 7],
        [8, 9]])


In [15]:
t = torch.ones(5)
print(f't: {t}', type(t))
n = t.numpy()
print(f'n: {n}', type(n))

t: tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
n: [1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [16]:
t.add_(1)
print(f't: {t}')
print(f'n: {n}')
# t.numpy() just like a pointer to tensor

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [17]:
print(f'{tensor} \n')
tensor.add_(5)
print(tensor)

tensor([[0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.]]) 

tensor([[5., 6., 7., 8.],
        [5., 6., 7., 8.],
        [5., 6., 7., 8.],
        [5., 6., 7., 8.]])


In [21]:
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n: {n}')
t.add_(1)
print(t)
print(n)

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
n =  np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out= n)
print(f't: {t}')
print(f'n: {n}')
# 不論從numpy 轉 tensor 或 tensor 轉 numpy 都 share same memory location
# 所以只要改變一個另一個就會跟著改變


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
